// Province code to name mappings for different locales
export const PROVINCE_NAMES = {
  en: {
    "IR-01": "Gilan",
    "IR-02": "Mazandaran",
    "IR-03": "E. Azerbaijan",
    "IR-04": "W. Azerbaijan",
    "IR-05": "Kermanshah",
    "IR-06": "Khuzestan",
    "IR-07": "Fars",
    "IR-08": "Kerman",
    "IR-09": "Razavi Khorasan",
    "IR-10": "Isfahan",
    "IR-11": "Sistan & Baluchestan",
    "IR-12": "Kurdistan",
    "IR-13": "Hamadan",
    "IR-14": "Chaharmahal & Bakhtiari",
    "IR-15": "Lorestan",
    "IR-16": "Ilam",
    "IR-17": "Kohgiluyeh & Boyer-Ahmad",
    "IR-18": "Bushehr",
    "IR-19": "Zanjan",
    "IR-20": "Semnan",
    "IR-21": "Yazd",
    "IR-22": "Hormozgan",
    "IR-23": "Tehran",
    "IR-24": "Ardabil",
    "IR-25": "Qom",
    "IR-26": "Qazvin",
    "IR-27": "Golestan",
    "IR-28": "N. Khorasan",
    "IR-29": "S. Khorasan",
    "IR-30": "Alborz",
    "IR-31": "Markazi",
  },
  fa: {
    "IR-01": "گیلان",
    "IR-02": "مازندران",
    "IR-03": "آذربایجان شرقی",
    "IR-04": "آذربایجان غربی",
    "IR-05": "کرمانشاه",
    "IR-06": "خوزستان",
    "IR-07": "فارس",
    "IR-08": "کرمان",
    "IR-09": "خراسان رضوی",
    "IR-10": "اصفهان",
    "IR-11": "سیستان و بلوچستان",
    "IR-12": "کردستان",
    "IR-13": "همدان",
    "IR-14": "چهارمحال و بختیاری",
    "IR-15": "لرستان",
    "IR-16": "ایلام",
    "IR-17": "کهگیلویه و بویراحمد",
    "IR-18": "بوشهر",
    "IR-19": "زنجان",
    "IR-20": "سمنان",
    "IR-21": "یزد",
    "IR-22": "هرمزگان",
    "IR-23": "تهران",
    "IR-24": "اردبیل",
    "IR-25": "قم",
    "IR-26": "قزوین",
    "IR-27": "گلستان",
    "IR-28": "خراسان شمالی",
    "IR-29": "خراسان جنوبی",
    "IR-30": "البرز",
    "IR-31": "مرکزی",
  },
} as const;

export function getProvinceName(
  code: string | null,
  locale: "en" | "fa" = "en"
): string | null {
  if (!code) return null;
  return PROVINCE_NAMES[locale][code as keyof typeof PROVINCE_NAMES.en] || code;
}
